name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 4 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.0.3
      - run: deno --version
      - run: deno test examples/01.tsx
      - run: deno test examples/03-async.tsx
