name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: denolib/setup-deno@master
      - run: deno --version
      - run: deno test examples/01.tsx
      - run: deno test examples/03-async.tsx
